apiVersion: v1
kind: Pod
metadata:
  name: cpu-test
  labels:
    app: cpu-test
spec:
  containers:
    - name: cpu-test
      image: busybox
      command:
        - /bin/sh
        - -c
        - while true; do :; done
      resources:
        requests:
          cpu: "100m"
          memory: "16Mi"
        limits:
          cpu: "500m"
          memory: "64Mi"